### ISSUE TITLE
Error: Command failed: ./scripts/attachConfirmUserTrigger.sh

### ISSUE THREAD

**Issue by Drengel1990** [aws-samples/aws-iot-chat-example#4]
Stack Trace --------------------------------------------
 
Error: Command failed: ./scripts/attachConfirmUserTrigger.sh

    at checkExecSyncError (child_process.js:490:13)
    at execSync (child_process.js:530:13)
    at commands.forEach.command (/Users/.../WebstormProjects/test/api/node_modules/serverless-hooks-plugin/serverless-hooks-plugin.js:17:26)
    at Array.forEach (native)
    at Object.hook (/Users/.../WebstormProjects/test/api/node_modules/serverless-hooks-plugin/serverless-hooks-plugin.js:14:18)
From previous event:
    at PluginManager.invoke (/Users/.../.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/Users/.../.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/Users/.../.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Serverless.run (/Users/.../.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/Users/.../.nvm/versions/node/v7.5.0/lib/node_modules/serverless/bin/serverless:42:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.5.0
     Serverless Version:     1.26.1

**Comment by yasithph** [comment]
getting the same error. does anyone know the solution to this?

**Comment by gretzky** [comment]
Check your aws configuration-- run through and make sure Default output type is JSON

**Comment by gretzky** [comment]
Run `aws configure` and make sure 'Default output type' is text or json

**Comment by borch84** [comment]
Hi I am having the same error. My default aws configure output is json

```
Serverless: Running after:aws:deploy:finalize:cleanup command: "./scripts/attachConfirmUserTrigger.sh"
 
  Error --------------------------------------------------
 
  Command failed: ./scripts/attachConfirmUserTrigger.sh
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Command failed: ./scripts/attachConfirmUserTrigger.sh
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at commands.forEach.command (/home/borch/Documents/JavaScript-Apps/aws-iot-chat-example/api/node_modules/serverless-hooks-plugin/serverless-hooks-plugin.js:17:26)
    at Array.forEach (<anonymous>)
    at Object.hook (/home/borch/Documents/JavaScript-Apps/aws-iot-chat-example/api/node_modules/serverless-hooks-plugin/serverless-hooks-plugin.js:14:18)

```

**Comment by JLee21** [comment]
@borch84 I ran into your problem, I think
Are you using an AWS profile other than the default one? Did you add the `profile` field in `api/serverless.yml`?
If so, try out my PR! #27

**Comment by Nosajool** [comment]
JLee's fix has been merged. Feel free to re-open if still seeing this error.
