### ISSUE TITLE
Error: Command failed: ./scripts/attachConfirmUserTrigger.sh

### ISSUE THREAD

**Issue by supun19** [aws-samples/aws-iot-chat-example#6]
Error: Command failed: ./scripts/attachConfirmUserTrigger.sh
./scripts/attachConfirmUserTrigger.sh: 8: ./scripts/attachConfirmUserTrigger.sh: Syntax error: "(" unexpected

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at commands.forEach.command (/opt/consult/iot-api/node_modules/serverless-hooks-plugin/serverless-hooks-plugin.js:17:26)
    at Array.forEach (<anonymous>)
    at Object.hook (/opt/consult/iot-api/node_modules/serverless-hooks-plugin/serverless-hooks-plugin.js:14:18)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>

could you someone help to this solve

**Comment by mdg215199** [comment]
Just now trying this repos, just in case anyone else has this same issue, please be sure to read the issue written in 09 https://github.com/aws-samples/aws-iot-chat-example/issues/9

It's the same issue.  As the original commented specified above, 

"So what's going on here? Within your .aws/credentials or .aws/config options, change the output field to json. Now, jq will be able to correctly parse the JSON results from the aws cli commands. The root cause is that you must have had the output set to text."

If you do this, you will have no issues.

**Comment by borch84** [comment]
Hi, I am having the same issue:
```
 Error --------------------------------------------------
 
  Command failed: ./scripts/attachConfirmUserTrigger.sh
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Command failed: ./scripts/attachConfirmUserTrigger.sh
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at commands.forEach.command (/home/borch/Documents/JavaScript-Apps/aws-iot-chat-example/api/node_modules/serverless-hooks-plugin/serverless-hooks-plugin.js:17:26)
    at Array.forEach (<anonymous>)
    at Object.hook (/home/borch/Documents/JavaScript-Apps/aws-iot-chat-example/api/node_modules/serverless-hooks-plugin/serverless-hooks-plugin.js:14:18)
From previous event:
    at PluginManager.invoke (/home/borch/.npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.run (/home/borch/.npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:439:17)
    at variables.populateService.then (/home/borch/.npm-global/lib/node_modules/serverless/lib/Serverless.js:109:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/home/borch/.npm-global/lib/node_modules/serverless/lib/Serverless.js:96:6)
    at serverless.init.then (/home/borch/.npm-global/lib/node_modules/serverless/bin/serverless:43:28)
    at /home/borch/.npm-global/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/borch/Documents/JavaScript-Apps/aws-iot-chat-example/api/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/borch/.npm-global/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at initializeErrorReporter.then (/home/borch/.npm-global/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /home/borch/.npm-global/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/home/borch/.npm-global/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           10.15.3
     Serverless Version:     1.41.1

```

**Comment by nanocosmos-ol** [comment]
I was having the same issue, it was related to a mismatch of aws config profiles and regions I needed to change the config.yml region setting which had hardcoded:
region: us-west-2
changed it to the default region of the aws config helped
